### ISSUE TITLE
Scrollbar doesn't work if the cursor is positioned outside it

### ISSUE THREAD

**Issue by feskyde** [solus-project/brisk-menu#23] opened 2017-01-31 15:17 UTC
- OS: Solus 2017.01.01.0
- Brisk version: 0.3.0

Same behavior as the old Budgie 8 menu:

https://youtu.be/vkg_NTfL_N4

**Comment by ikeydoherty** [comment] 2017-01-31 21:05
Yep, duplicate of #3

**Closed by ikeydoherty** 2017-01-31 21:05 UTC

**Comment by feskyde** [comment] 2017-01-31 21:24
Oh issues search why are you so broken? 😕

**Comment by ikeydoherty** [comment] 2017-01-31 22:00
Yeah its.. meh.
