### ISSUE TITLE
Keyboard navigation: down arrow does nothing after search

### ISSUE THREAD

**Issue by epgfm** [solus-project/brisk-menu#66] opened 2017-08-16 08:39 UTC
Activate, type in "ter" and say you want to select "LibreOffice Writer" from the shortlisted applications.
One would expect to be able to hit the down arrow, the same way one can use the up arrow to circle through matches in reverse order.
However, currently the down arrow key does not start scrolling (one would expect from the top) through the shortlisted applications.

**Comment by flexiondotorg** [comment] 2017-08-16 09:06
This is a duplicate of #22 and can be closed.

**Closed** 2017-08-16 09:06 UTC
