### ISSUE TITLE
Scroll bar gets stuck when scrolling

### ISSUE THREAD

**Issue by baimafeima** [solus-project/brisk-menu#31] opened 2017-05-09 11:47 UTC
The scroll bar on the right side of Brisk Menu gets stuck when scrolling it. 

How to reproduce: 
Left click on the scroll bar and keep the button pressed **while** moving a pointing stick or mouse (in my case Lenovo TrackPoint) up or down.

**Comment by flexiondotorg** [comment] 2017-05-11 06:27
Duplicate of  #3.

**Comment by ikeydoherty** [comment] 2017-05-16 20:35
Ah yeah dupe ty :)

**Closed by ikeydoherty** 2017-05-16 20:35 UTC
