### ISSUE TITLE
menu not updated after new applications are installed

### ISSUE THREAD

**Issue by snkiz** [solus-project/brisk-menu#25] opened 2017-03-15 15:00 UTC
Every time I install a new app in Solus I have to log out and back in to get brisk to see new applications. Is this not implemented or just not working?

**Comment by flexiondotorg** [comment] 2017-03-17 14:22
I can't reproduce this issue on Ubuntu MATE 17.04 with Brisk Menu 0.3.0.

**Comment by ikeydoherty** [comment] 2017-03-17 14:48
@flexiondotorg I think Ubuntu is carrying a patched menus library. I know `gnome-menus` is patched for Unity, and the patch actually caused problems (and then solutions..) in Budgie. We have the same issue with vanilla packaging in Solus, so if there is one to be found we should merge it into Solus..

**Comment by ikeydoherty** [comment] 2017-03-17 14:49
Scratch that - package in Ubuntu (Yakkety and Zesty) are vanilla. Only `gnome-menus` is patched

**Comment by ikeydoherty** [comment] 2017-03-17 14:52
Ubuntu Unity issue (`gnome-menus`): https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1506744

Crash that exposed the issue in Budgie: https://github.com/budgie-desktop/budgie-desktop/issues/632

Relevant file: `debian/80_file_monitor_delayed.patch`

**Comment by ikeydoherty** [comment] 2017-03-17 14:54
Can confirm that the latest revision of the patch actually fixes the crash that hit Budgie:

**Comment by flexiondotorg** [comment] 2017-05-11 06:36
@ikeydoherty I've not experienced any issues with `mate-menus`, have you?

**Comment by ikeydoherty** [comment] 2017-05-11 06:50
Yep - raised it on IRC a while back. Need to port that patch

**Comment by ikeydoherty** [comment] 2017-05-18 22:46
This is now fixed in git master by relying on our own idle updates mechanism wrapping `GAppInfoMonitor`

**Closed by ikeydoherty** 2017-05-18 22:46 UTC
Labels: bug
